name: deployment-workflow
on: [push,workflow_dispatch]
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v5
      - name: Install Node application
        uses: actions/setup-node@v6
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Linting Node code
        run : npm run lint
      - name: Running Node tests
        run: npm run test
      - name: Building the node package
        run: npm run build
      - name: Deploy the package
        run: echo "Deploying..."
      